# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "uas" "virtio_pci" "virtio_net" "virtio_blk" "virtio_scsi" "virtio_balloon" "virtio_console" "virtio_rng"];
  # boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "virtio_pci" "virtio_net" "virtio_blk" "virtio_scsi" "virtio_balloon" "virtio_console" "virtio_rng"];
  boot.extraModulePackages = [];
  # "console=ttyS0"
  boot.kernelParams = ["default_hugepagesz=1G" "hugepagesz=1G" "hugepages=0" "amd_pstate=active" "amd_pstate.shared_mem=1" "brd.rd_nr=1" "brd.rd_size=11240000"];
  boot.extraModprobeConfig = ''
    options kvm_amd nested=1
    softdep nvme pre: vfio-pci
  ''; # for amd cpu

  virtualisation.vfio = {
    enable = true;
    IOMMUType = "amd";
    applyACSpatch = false;
    ignoreMSRs = true;
    devices = [
      #   "10de:2684" # Graphics
      #   "10de:22ba" # Audio
      # "8086:f1a6" # nvme

      # "10de:21c4" # GTX 1650 Super
      # "10de:1aeb"
      # "10de:1aec"
      # "10de:1aed"
    ];
    blacklistNvidia = false;
  };

  hardware.mlx5 = {
    enable = true;
    enableSRIOV = true;
    interfaces = ["mlx5_0"];
  };

  fileSystems."/system" = {
    device = "/dev/disk/by-label/fluent_system";
    options = ["compress=zstd" "noatime"];
    fsType = "btrfs";
    neededForBoot = true;
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-label/fluent_system";
    options = ["subvol=@tmp" "compress=zstd" "noatime"];
    fsType = "btrfs";
    neededForBoot = true;
  };

  fileSystems."/system/persistent" = {
    device = "/dev/disk/by-label/fluent_system";
    options = ["subvol=@persistent" "compress=zstd" "noatime"];
    fsType = "btrfs";
    neededForBoot = true;
  };

  fileSystems."/system/var" = {
    device = "/dev/disk/by-label/fluent_system";
    options = ["subvol=@nix-var" "compress=zstd" "noatime"];
    fsType = "btrfs";
    neededForBoot = true;
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-label/fluent_boot";
    fsType = "vfat";
  };

  swapDevices = [];

  # systemd.sleep.extraConfig = "
  #   AllowSuspend=no
  #   AllowHibernation=no
  #   AllowHybridSleep=no
  #   AllowSuspendThenHibernate=no
  # ";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
