# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."emby" = {
    image = "linuxserver/emby:4.9.1";
    environment = {
      "DOCKER_MODS" = "272567571/mods:emby-crack";
      "EMBY_CRACK_URL" = "https://emby-crack.int4byte.org";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Shanghai";
    };
    volumes = [
      "/home/wf/Data/emby/config:/config:rw"
      "/share:/media:rw"
    ];
    ports = [
      "8096:8096/tcp"
    ];
    dependsOn = [
      "emby-caddy"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=emby"
      "--network=emby_default"
    ];
  };
  systemd.services."podman-emby" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-emby_default.service"
    ];
    requires = [
      "podman-network-emby_default.service"
    ];
    partOf = [
      "podman-compose-emby-root.target"
    ];
    wantedBy = [
      "podman-compose-emby-root.target"
    ];
  };
  virtualisation.oci-containers.containers."emby-caddy" = {
    image = "ghcr.io/caddybuilds/caddy-cloudflare:latest";
    volumes = [
      "/home/wf/Data/emby/Caddyfile:/etc/caddy/Caddyfile:rw"
      "/home/wf/Data/emby/caddy_config:/config:rw"
      "/home/wf/Data/emby/caddy_data:/data:rw"
      "/home/wf/Data/emby/site:/srv:rw"
    ];
    ports = [
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=caddy"
      "--network=emby_default"
    ];
  };
  systemd.services."podman-emby-caddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-emby_default.service"
    ];
    requires = [
      "podman-network-emby_default.service"
    ];
    partOf = [
      "podman-compose-emby-root.target"
    ];
    wantedBy = [
      "podman-compose-emby-root.target"
    ];
  };
  virtualisation.oci-containers.containers."metatube" = {
    image = "ghcr.io/metatube-community/metatube-server:latest";
    environment = {
      "HTTPS_PROXY" = "";
      "HTTP_PROXY" = "";
    };
    volumes = [
      "emby_run:/var/run:rw"
    ];
    cmd = [ "-dsn" "postgres://metatube:metatube@/metatube?host=/var/run/postgresql" "-port" "8080" "-db-auto-migrate" "-db-prepared-stmt" ];
    dependsOn = [
      "metatube-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=metatube"
      "--network=emby_default"
    ];
  };
  systemd.services."podman-metatube" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-emby_default.service"
      "podman-volume-emby_run.service"
    ];
    requires = [
      "podman-network-emby_default.service"
      "podman-volume-emby_run.service"
    ];
    partOf = [
      "podman-compose-emby-root.target"
    ];
    wantedBy = [
      "podman-compose-emby-root.target"
    ];
  };
  virtualisation.oci-containers.containers."metatube-postgres" = {
    image = "postgres:15-alpine";
    environment = {
      "POSTGRES_DB" = "metatube";
      "POSTGRES_PASSWORD" = "metatube";
      "POSTGRES_USER" = "metatube";
    };
    volumes = [
      "/home/wf/Data/emby/db:/var/lib/postgresql/data:rw"
      "emby_run:/var/run:rw"
    ];
    cmd = [ "-c" "TimeZone=Asia/Shanghai" "-c" "log_timezone=Asia/Shanghai" "-c" "listen_addresses=" "-c" "unix_socket_permissions=0777" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=emby_default"
    ];
  };
  systemd.services."podman-metatube-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-emby_default.service"
      "podman-volume-emby_run.service"
    ];
    requires = [
      "podman-network-emby_default.service"
      "podman-volume-emby_run.service"
    ];
    partOf = [
      "podman-compose-emby-root.target"
    ];
    wantedBy = [
      "podman-compose-emby-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-emby_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f emby_default";
    };
    script = ''
      podman network inspect emby_default || podman network create emby_default
    '';
    partOf = [ "podman-compose-emby-root.target" ];
    wantedBy = [ "podman-compose-emby-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-emby_run" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect emby_run || podman volume create emby_run
    '';
    partOf = [ "podman-compose-emby-root.target" ];
    wantedBy = [ "podman-compose-emby-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-emby-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}