# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mybili-mybili" = {
    image = "docker.io/pharra/mybili:latest";
    environment = {
      "DB_CONNECTION" = "sqlite";
      "DB_DATABASE" = "/data/database.sqlite";
      "REDIS_DB" = "3";
      "REDIS_HOST" = "redis";
    };
    volumes = [
      "/share/bilibili/data:/app/storage/app/public:rw"
      "/share/bilibili/mybili-data:/data:rw"
    ];
    ports = [
      "5151:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mybili"
      "--network=mybili_default"
    ];
  };
  systemd.services."podman-mybili-mybili" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-mybili_default.service"
    ];
    requires = [
      "podman-network-mybili_default.service"
    ];
    partOf = [
      "podman-compose-mybili-root.target"
    ];
    wantedBy = [
      "podman-compose-mybili-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mybili-redis" = {
    image = "docker.io/redis";
    volumes = [
      "/share/bilibili/redis:/data:rw"
    ];
    cmd = ["redis-server" "--save" "60" "1" "--loglevel" "warning"];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=mybili_default"
    ];
  };
  systemd.services."podman-mybili-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-mybili_default.service"
    ];
    requires = [
      "podman-network-mybili_default.service"
    ];
    partOf = [
      "podman-compose-mybili-root.target"
    ];
    wantedBy = [
      "podman-compose-mybili-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-mybili_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f mybili_default";
    };
    script = ''
      podman network inspect mybili_default || podman network create mybili_default
    '';
    partOf = ["podman-compose-mybili-root.target"];
    wantedBy = ["podman-compose-mybili-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mybili-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
