# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."magnet-crawler" = {
    image = "pharra/magnet:latest";
    environment = {
      "PYTHONUNBUFFERED" = "1";
      "TZ" = "Asia/Shanghai";
    };
    volumes = [
      "/home/wf/Data/magnet/data:/app/data:rw"
      "/home/wf/Data/magnet/logs:/app/logs:rw"
    ];
    ports = [
      "8000:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=SYS_ADMIN"
      "--network-alias=magnet-crawler"
      "--network=magnet_default"
      "--shm-size=1073741824"
    ];
  };
  systemd.services."podman-magnet-crawler" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-magnet_default.service"
    ];
    requires = [
      "podman-network-magnet_default.service"
    ];
    partOf = [
      "podman-compose-magnet-root.target"
    ];
    wantedBy = [
      "podman-compose-magnet-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-magnet_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f magnet_default";
    };
    script = ''
      podman network inspect magnet_default || podman network create magnet_default
    '';
    partOf = [ "podman-compose-magnet-root.target" ];
    wantedBy = [ "podman-compose-magnet-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-magnet-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}