-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:LG Electronics LG TV SSCR2 0x01010101", mode = "3840x2160@119.880", position = "0x0", scale = 2, vrr = 0, bitdepth = 10, cm = "hdr" })
