# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  sops.secrets."substore.env" = {
    sopsFile = ./substore.env;
    format = "dotenv";
  };
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sub-store" = {
    image = "docker.io/xream/sub-store:latest";
    environment = {
      "SUB_STORE_BACKEND_API_HOST" = "0.0.0.0";
      "SUB_STORE_BACKEND_API_PORT" = "3001";
      "SUB_STORE_BACKEND_MERGE" = "true";
    };
    environmentFiles = [
      config.sops.secrets."substore.env".path
    ];
    volumes = [
      "/home/wf/Data/substore/data:/opt/app/data:rw"
    ];
    ports = [
      "3001:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sub-store"
      "--network=substore_default"
    ];
  };
  systemd.services."podman-sub-store" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-substore_default.service"
    ];
    requires = [
      "podman-network-substore_default.service"
    ];
    partOf = [
      "podman-compose-substore-root.target"
    ];
    wantedBy = [
      "podman-compose-substore-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-substore_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f substore_default";
    };
    script = ''
      podman network inspect substore_default || podman network create substore_default
    '';
    partOf = ["podman-compose-substore-root.target"];
    wantedBy = ["podman-compose-substore-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-substore-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
