# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."bili-sync-rs" = {
    image = "docker.io/amtoaer/bili-sync-rs:latest";
    volumes = [
      "/home/wf/Data/emby/config/metadata/people:/app/.config/bili-sync/upper_face:rw"
      "/share/bilisync/.config:/app/.config/bili-sync:rw"
      "/share/bilisync/downloads:/downloads:rw"
    ];
    ports = [
      "12345:12345/tcp"
    ];
    user = "1000:100";
    log-driver = "journald";
    extraOptions = [
      "--hostname=bili-sync-rs"
      "--network-alias=bili-sync-rs"
      "--network=bridge"
    ];
  };
  systemd.services."podman-bili-sync-rs" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-bilisync-root.target"
    ];
    wantedBy = [
      "podman-compose-bilisync-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-bilisync-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
