# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  sops.secrets."xray" = {
    sopsFile = ./xray.json;
    format = "json";
    key = "";
  };

  services.xray = {
    enable = true;
    settingsFile = config.sops.secrets."xray".path;
  };
}
