# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."cookiecloud-app" = {
    image = "docker.io/easychen/cookiecloud:latest";
    volumes = [
      "/home/wf/Data/cookiecloud/data:/data/api/data:rw"
    ];
    ports = [
      "8088:8088/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=cookiecloud"
      "--network=cookiecloud_default"
    ];
  };
  systemd.services."podman-cookiecloud-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-cookiecloud_default.service"
    ];
    requires = [
      "podman-network-cookiecloud_default.service"
    ];
    partOf = [
      "podman-compose-cookiecloud-root.target"
    ];
    wantedBy = [
      "podman-compose-cookiecloud-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-cookiecloud_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f cookiecloud_default";
    };
    script = ''
      podman network inspect cookiecloud_default || podman network create cookiecloud_default
    '';
    partOf = ["podman-compose-cookiecloud-root.target"];
    wantedBy = ["podman-compose-cookiecloud-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-cookiecloud-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
