# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."clouddrive2" = {
    image = "cloudnas/clouddrive2";
    environment = {
      "CLOUDDRIVE_HOME" = "/Config";
      "TZ" = "Asia/Shanghai";
    };
    volumes = [
      "/home/wf/Data/clouddrive2/config:/Config:rw"
    ];
    ports = [
      "19798:19798/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/fuse:/dev/fuse:rwm"
      "--network-alias=cloudnas"
      "--network=clouddrive2_default"
    ];
  };
  systemd.services."podman-clouddrive2" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-clouddrive2_default.service"
    ];
    requires = [
      "podman-network-clouddrive2_default.service"
    ];
    partOf = [
      "podman-compose-clouddrive2-root.target"
    ];
    wantedBy = [
      "podman-compose-clouddrive2-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-clouddrive2_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f clouddrive2_default";
    };
    script = ''
      podman network inspect clouddrive2_default || podman network create clouddrive2_default
    '';
    partOf = ["podman-compose-clouddrive2-root.target"];
    wantedBy = ["podman-compose-clouddrive2-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-clouddrive2-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
