# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  sops.secrets = {
    "token" = {
      sopsFile = ./caddy.yaml;
    };
    "domain" = {
      sopsFile = ./caddy.yaml;
    };
    "email" = {
      sopsFile = ./caddy.yaml;
    };
  };

  sops.templates."Caddyfile".content = ''
    {
      http_port 8001
      https_port 8443
      email ${config.sops.placeholder."email"}
      acme_dns cloudflare ${config.sops.placeholder."token"}
      servers {
              timeouts {
              read_body   10m
              read_header 10m
              write       10m
              idle        10m
              }
      }
    }

    emby.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:8096
    }

    immich.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:2283
    }

    reader.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:4396
    }

    substore.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:3001
    }


    mybili.${config.sops.placeholder."domain"} {
            encode gzip
            header Content-Security-Policy "upgrade-insecure-requests"
            reverse_proxy 127.0.0.1:5151
    }

    clouddrive2.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy h2c://127.0.0.1:19798 {
                flush_interval -1
            }
    }

    magnet.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:8000
    }

    mihomo.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:9090
    }

    openreader.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:8068
    }

    cookiecloud.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:8088
    }

    bilisync.${config.sops.placeholder."domain"} {
            encode gzip
            reverse_proxy 127.0.0.1:12345
    }
  '';

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."caddy-caddy" = {
    image = "ghcr.io/caddybuilds/caddy-cloudflare:latest";
    volumes = [
      "${config.sops.templates."Caddyfile".path}:/etc/caddy/Caddyfile:rw"
      "/home/wf/Data/caddy/caddy_config:/config:rw"
      "/home/wf/Data/caddy/caddy_data:/data:rw"
      "/home/wf/Data/caddy/site:/srv:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-caddy-caddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-caddy-root.target"
    ];
    wantedBy = [
      "podman-compose-caddy-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-caddy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
