# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  iscsi-scripts = pkgs.writeShellScriptBin "iscsi-scripts" ''
    ${pkgs.openiscsi}/bin/iscsiadm -m discovery -t sendtargets -p homelab.local
    ${pkgs.openiscsi}/bin/iscsiadm -m node -p homelab.local --targetname=iqn.2016-06.io.spdk:nixos --login
  '';
in {
  imports = [
    (modulesPath + "/installer/netboot/netboot-minimal.nix")
  ];

  services = {
    openiscsi = {
      enable = true;
      name = "iqn.2020-08.org.linux-iscsi.initiatorhost:installer";
    };
  };

  environment.systemPackages = with pkgs; [
    rsync
    git
    iscsi-scripts
  ];

  boot.kernelParams = lib.mkForce ["nogpumanager" "nvidia_drm.modeset=0"];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
}
