# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  mysecrets,
  ...
}: {
  sops.secrets."reader.env" = {
    sopsFile = ./reader.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."reader" = {
    image = "docker.io/pharra/reader:latest";
    environmentFiles = [
      config.sops.secrets."reader.env".path
    ];
    volumes = [
      "/home/wf/Data/reader/logs:/logs:rw"
      "/home/wf/Data/reader/storage:/storage:rw"
      "/share/sftp/Android/Documents/小说:/storage/emulated/0/Documents/小说:rw"
    ];
    ports = [
      "4396:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=reader"
      "--network=reader_default"
    ];
  };
  systemd.services."podman-reader" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-reader_default.service"
    ];
    requires = [
      "podman-network-reader_default.service"
    ];
    partOf = [
      "podman-compose-reader-root.target"
    ];
    wantedBy = [
      "podman-compose-reader-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-reader_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f reader_default";
    };
    script = ''
      podman network inspect reader_default || podman network create reader_default
    '';
    partOf = ["podman-compose-reader-root.target"];
    wantedBy = ["podman-compose-reader-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-reader-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
