name: NixOS

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        hostname:
          - homelab_kde
          - zed_kde

    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Free disk space for Nix"
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave' # holster, carve, cleave (default), rampage

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: nixpkgs-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: "Build ${{ matrix.config_name }} NixOS config ❄️"
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L
