mihomo:
    providers:
        yiyuan: ENC[AES256_GCM,data:fwNyqpB9uSVS2hM25IWRZDJa72IMrAD73DzgswJwNt/6oeOaZ1nvpYzgiY6GE+t8TQ83GO+XrMmHHCzXIaCrmSxMi96rsIIXLMetICIiGemgDjZx,iv:O9r5PdcYMIH/7ZtZY65Ci4jzzScltV7O1qrAqpCgVnk=,tag:yll9wK/MSGIJLzlX3P2KzQ==,type:str]
        llg: ENC[AES256_GCM,data:PQsJbR2rgtYM4j8N2av2/EcR2hSD5Kp8dWalgk2Dw6u3An4deBqqsg+Igq4WyEUYMMz21/CvHM43t4/uIILIGDTTxql8m1kn6FcT0ZpF,iv:aygTx1CZro+ATgi62kRzbWn3XVCd8z81nAp/ab4eEZc=,tag:/EbG6oyFf22m5KebM3O0tA==,type:str]
        l666: ENC[AES256_GCM,data:mNoE1eP08c8nYl6aQBOlkgaqVPGwzxTh0zw+eiTgAZMcPkSha9UgOXRivO+FwLUEBakZDeDcFveBBEdZK7B/DPNfxH/fgNQR6/zJ4xXkEXrXhKEuyAg=,iv:s2mWS6+Vrgl4yt12Hlb8KCLUgX9Z1FedKwUySRQeoHo=,tag:z2jlGcRJ0NePwDbX22de3A==,type:str]
        paofu: ENC[AES256_GCM,data:LsSPGO24o9EtJ5JIo+VgzTuBW+PEDEpYr6P85vvz63W20iVUesJSK6E/Fgl8xaoBSCllU476dOrdPBpJe7j7MulFIzJTtplpuUcj8nQVgAq7I0xUKq7BzB17oRIFCzmo3oW9rvguym6BB+oI5ZGd15HeG9sPOmqp8aX6v/953UP43VBNZhveY9ER0ls2rDYbhy8+CUqXqI6JRq/GM6Umn7zUwvafFN6JnOQhsY2AdNyH3INlXSylH+KBlGmyifuDtUyW1f3agyDOu7n7TW/CMvvEpJDAkO9yD4kcrZg7sLPXJUzo9WHJz5PEyZZpnbTevegXd9N3x+lEJ5sR3dhvk/AsQtcRcaxU5Kat8DQuTL6iTUaBmyKrzK7CyMa8GxcRnXFnnywKsPX9kBsqwTrYochCr3LCTpSGWPgVYX6Jce7oCaQav1CHi+SWY1I7BheaPS2aQMQTQw==,iv:gPQYCncw8Mf7gqhPBqs2pvzGgoSIfj0mk2lySSCEYUw=,tag:JytF5OWo0ec9vpNYAZBbVQ==,type:str]
sops:
    age:
        - recipient: age14ckewpst7ua5acm0hndfps0mjfl3yd0gwhxn7pn379hgyvhs8urse7xt5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0YrMS9xcDlodEpPNkdP
            L3ZBeEY0d3M0ZUZLUERWQjU5dXdmTzZHUEVZCnh0cXc5UFlGTWEvZmQ3OFFoK0dq
            K25LamhpWEFxZkhhOUFYZU9mdGU4YUEKLS0tIE1Gd2M3cWlWcFdsMitHOFRxbEhs
            VjlPYzB3YU1sMUtGV280bWpybjJSQkEKZoHMwpG7a5FG7qxfRI4L5giO5zLSageL
            TD3Dq9hiMutxw1C52ZpahmxQOyVK0es+pvibMnVs6Ll6fEZpI9Ir9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j66ujjkvpy7cffu5q83cucnweqk78k5z5sch3cyz8hgqhzsu4d8sj4086c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEpnTmtxMkhzbzNGOExh
            SjhEZk5KdEsrY0RnZDJwMkMxUTBIU3lweVZJCnQ3Ujd4ZnVpcW9TYjZiR2xoaG1n
            RXdiajB2MkordENkdlhhTlJER2dwcUkKLS0tIEQxUS9RYkVJWElwS2wvUFRPZ2FR
            WUlremcxK3R3dkkrUG5LVXYraXM3WFEKXe5SUotec2H3I3RvsNtnBt0zyVCdySMG
            L+z4YccTHAaV24HXbfZEWLVhMcGFxIYIsSHzY8MQfcoJKnJxDMYsUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13chrgdcw55zhzzmjtlu9jhmjn2lt55rrlkx0h7kpu2gnaaz6u52qwzd0qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXVsR0ZDSU9pVm0rMFBs
            TFFRbVJYRk1yZ0x5dndvUDRCNFA0WUJZZTI4CmhWZEV2ZXVWbjJ2aWZOZEhhR1pV
            aGxiSno4UkNwT05OeVdrVG9XTzY0QlEKLS0tIDdjZ3k2TE9LYlloa2krcXVZRHgx
            RmNQdHlYYWRoT0pxV2lSdzcwNnJaUmMKIOV8KBPITMjHef3Fk35TMizwJxUk0DS2
            a5/dkHbc2h17ZZdnf2ifRFGRHobOgFEdPaM17g9r4ei8d5PO764p6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T08:12:35Z"
    mac: ENC[AES256_GCM,data:FzA9hzlEWKj7nbv/Ug9Sg4hl+jKyLC3uj6l1QwWF9WZKkRNGDyJkd2NQ1btdC5sila9TVtVb70wUEXfS2PTwZ1Xa4iCLr9rfNFwBJ92DeeiA7edc7nuJurJQgLBF0CPVNIu5S/yZ2VvmeFTZhjFZfvaQkrSdsPJQQNaS+RWMm8M=,iv:l+R6IYEctsMJXuquAff6IvxDY2I8uxSYReN1gRT+lTU=,tag:wR2zxUGspkDSimvsVXshvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
