mihomo:
    providers:
        yiyuan: ENC[AES256_GCM,data:fwNyqpB9uSVS2hM25IWRZDJa72IMrAD73DzgswJwNt/6oeOaZ1nvpYzgiY6GE+t8TQ83GO+XrMmHHCzXIaCrmSxMi96rsIIXLMetICIiGemgDjZx,iv:O9r5PdcYMIH/7ZtZY65Ci4jzzScltV7O1qrAqpCgVnk=,tag:yll9wK/MSGIJLzlX3P2KzQ==,type:str]
        llg: ENC[AES256_GCM,data:mkeBKFwTWpur0FNJlrWslqDgLCVhXxs01auhqxMcTXxi39g2CJmdFXhF134SSO96Mq5acBOeVYIr+kf6QII4Ohn5+YnL2TZZw4e5t6XBy9aZZdRdGs78EhULv9QPRItK/rsE,iv:4NzT6zaGYaspAu5UTGuFqjpUZjRyFyFeBRbDHl3PHog=,tag:5AzZxlgMBh38iZyh+WyzTQ==,type:str]
        l666: ENC[AES256_GCM,data:L6BgYIfpRGGPhZHtE7j4ReGJLgqvrtpmJIkZ1x1GsYXaoA2yKDGKXwd+KOWPxnbjzyIlstlw8bffuF0EIR4eum7Um6whwCcDXv+qKklZebDk/4Q9evBc1BshMClr/A==,iv:uZ/QYqoMDlT/h/zretcKL5y+U+lUk31LbNKv1Rm7+Pw=,tag:w12aQriFOGZoEzjLrKTBXw==,type:str]
sops:
    age:
        - recipient: age14ckewpst7ua5acm0hndfps0mjfl3yd0gwhxn7pn379hgyvhs8urse7xt5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0YrMS9xcDlodEpPNkdP
            L3ZBeEY0d3M0ZUZLUERWQjU5dXdmTzZHUEVZCnh0cXc5UFlGTWEvZmQ3OFFoK0dq
            K25LamhpWEFxZkhhOUFYZU9mdGU4YUEKLS0tIE1Gd2M3cWlWcFdsMitHOFRxbEhs
            VjlPYzB3YU1sMUtGV280bWpybjJSQkEKZoHMwpG7a5FG7qxfRI4L5giO5zLSageL
            TD3Dq9hiMutxw1C52ZpahmxQOyVK0es+pvibMnVs6Ll6fEZpI9Ir9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j66ujjkvpy7cffu5q83cucnweqk78k5z5sch3cyz8hgqhzsu4d8sj4086c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEpnTmtxMkhzbzNGOExh
            SjhEZk5KdEsrY0RnZDJwMkMxUTBIU3lweVZJCnQ3Ujd4ZnVpcW9TYjZiR2xoaG1n
            RXdiajB2MkordENkdlhhTlJER2dwcUkKLS0tIEQxUS9RYkVJWElwS2wvUFRPZ2FR
            WUlremcxK3R3dkkrUG5LVXYraXM3WFEKXe5SUotec2H3I3RvsNtnBt0zyVCdySMG
            L+z4YccTHAaV24HXbfZEWLVhMcGFxIYIsSHzY8MQfcoJKnJxDMYsUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13chrgdcw55zhzzmjtlu9jhmjn2lt55rrlkx0h7kpu2gnaaz6u52qwzd0qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXVsR0ZDSU9pVm0rMFBs
            TFFRbVJYRk1yZ0x5dndvUDRCNFA0WUJZZTI4CmhWZEV2ZXVWbjJ2aWZOZEhhR1pV
            aGxiSno4UkNwT05OeVdrVG9XTzY0QlEKLS0tIDdjZ3k2TE9LYlloa2krcXVZRHgx
            RmNQdHlYYWRoT0pxV2lSdzcwNnJaUmMKIOV8KBPITMjHef3Fk35TMizwJxUk0DS2
            a5/dkHbc2h17ZZdnf2ifRFGRHobOgFEdPaM17g9r4ei8d5PO764p6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T16:05:48Z"
    mac: ENC[AES256_GCM,data:8Iy90wNIlcEJRCRMTdM9CLMsqLBECOIFj/k008mxKucpTsizGmfQgszSpc3snZ+ruJvh9joUE+h6IJCN39KeCb32tocF0CQSK9sgNkqo4VrRukMw0PHE9zP+odDc6NJhJwXarPZ4HN4wD5ISfV/GF2N6sGoKvnLm+UrJCdAKqGA=,iv:iEkkEooL37XFo5uD3jDSZ5u3zr0/SQsxhtXVeeJkWxc=,tag:+5HKnRUAQgThpI0iCTGHGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
