mihomo:
    providers:
        substore: ENC[AES256_GCM,data:e48sRQuCfl8MbCkNRFTGFtum5kICasdlJOnkryVwdXv/zdw5175+dwkHWVHbt4KDSqG5jy/6U5Udo91sHl4aqfw5CqMLywo+RYJDocvCHsguAzq2bfSMxiZ9V+arUrQtAVfvpWJ7q+1Y+yAGiHl3xp1DDcNbTHH+QSQY8asEXBKairaHQcUP6uqHphgASOcnCDAFgRkgtWMDEhCnO+Ah8rckakZRTEk=,iv:2rQ6e9aiXGlDMqhv3r+3Q6j4nGWYZvbNElNlap/NHvw=,tag:iIQAJc0DWE+EJdj8d2ixbQ==,type:str]
easytier:
    int4byte:
        secret: ENC[AES256_GCM,data:g5vSXi/09kBvGHNHWKtG6M2GHDeX5wB57ADFUph3VXsDIX8tjKc+wg==,iv:m7Nc8K4b/OLtwDQoy7nmEYGmfogV/hqAgIh3GLgZkW0=,tag:JL5PW+12GSTOPD5HNHWbdQ==,type:str]
sops:
    age:
        - recipient: age14ckewpst7ua5acm0hndfps0mjfl3yd0gwhxn7pn379hgyvhs8urse7xt5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0YrMS9xcDlodEpPNkdP
            L3ZBeEY0d3M0ZUZLUERWQjU5dXdmTzZHUEVZCnh0cXc5UFlGTWEvZmQ3OFFoK0dq
            K25LamhpWEFxZkhhOUFYZU9mdGU4YUEKLS0tIE1Gd2M3cWlWcFdsMitHOFRxbEhs
            VjlPYzB3YU1sMUtGV280bWpybjJSQkEKZoHMwpG7a5FG7qxfRI4L5giO5zLSageL
            TD3Dq9hiMutxw1C52ZpahmxQOyVK0es+pvibMnVs6Ll6fEZpI9Ir9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j66ujjkvpy7cffu5q83cucnweqk78k5z5sch3cyz8hgqhzsu4d8sj4086c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEpnTmtxMkhzbzNGOExh
            SjhEZk5KdEsrY0RnZDJwMkMxUTBIU3lweVZJCnQ3Ujd4ZnVpcW9TYjZiR2xoaG1n
            RXdiajB2MkordENkdlhhTlJER2dwcUkKLS0tIEQxUS9RYkVJWElwS2wvUFRPZ2FR
            WUlremcxK3R3dkkrUG5LVXYraXM3WFEKXe5SUotec2H3I3RvsNtnBt0zyVCdySMG
            L+z4YccTHAaV24HXbfZEWLVhMcGFxIYIsSHzY8MQfcoJKnJxDMYsUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13chrgdcw55zhzzmjtlu9jhmjn2lt55rrlkx0h7kpu2gnaaz6u52qwzd0qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXVsR0ZDSU9pVm0rMFBs
            TFFRbVJYRk1yZ0x5dndvUDRCNFA0WUJZZTI4CmhWZEV2ZXVWbjJ2aWZOZEhhR1pV
            aGxiSno4UkNwT05OeVdrVG9XTzY0QlEKLS0tIDdjZ3k2TE9LYlloa2krcXVZRHgx
            RmNQdHlYYWRoT0pxV2lSdzcwNnJaUmMKIOV8KBPITMjHef3Fk35TMizwJxUk0DS2
            a5/dkHbc2h17ZZdnf2ifRFGRHobOgFEdPaM17g9r4ei8d5PO764p6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T03:49:48Z"
    mac: ENC[AES256_GCM,data:1JOiim/wasw0FPHV8nL6ZxisWIA11wQSpV8irapG26XPiQ/yHwzuYG5/iPktnkEY8z0nffDeh9GWxn8Gz90ZoZCfT5JmpoNYzhCDMGwd8Ln+Q7K+k1yVFZnzibG6whB+dLW/bi5fH4PxB4eGGIgCBHIJFVXKL7+IRZ6rJkj4n44=,iv:9PaeghQq2LHBcq5vHOwiDksI8466oVtHT9bmVshy0IM=,tag:zrUevT4+//Hqsutk/cdJ0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
