mihomo:
    providers:
        substore: ENC[AES256_GCM,data:e48sRQuCfl8MbCkNRFTGFtum5kICasdlJOnkryVwdXv/zdw5175+dwkHWVHbt4KDSqG5jy/6U5Udo91sHl4aqfw5CqMLywo+RYJDocvCHsguAzq2bfSMxiZ9V+arUrQtAVfvpWJ7q+1Y+yAGiHl3xp1DDcNbTHH+QSQY8asEXBKairaHQcUP6uqHphgASOcnCDAFgRkgtWMDEhCnO+Ah8rckakZRTEk=,iv:2rQ6e9aiXGlDMqhv3r+3Q6j4nGWYZvbNElNlap/NHvw=,tag:iIQAJc0DWE+EJdj8d2ixbQ==,type:str]
sops:
    age:
        - recipient: age14ckewpst7ua5acm0hndfps0mjfl3yd0gwhxn7pn379hgyvhs8urse7xt5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0YrMS9xcDlodEpPNkdP
            L3ZBeEY0d3M0ZUZLUERWQjU5dXdmTzZHUEVZCnh0cXc5UFlGTWEvZmQ3OFFoK0dq
            K25LamhpWEFxZkhhOUFYZU9mdGU4YUEKLS0tIE1Gd2M3cWlWcFdsMitHOFRxbEhs
            VjlPYzB3YU1sMUtGV280bWpybjJSQkEKZoHMwpG7a5FG7qxfRI4L5giO5zLSageL
            TD3Dq9hiMutxw1C52ZpahmxQOyVK0es+pvibMnVs6Ll6fEZpI9Ir9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j66ujjkvpy7cffu5q83cucnweqk78k5z5sch3cyz8hgqhzsu4d8sj4086c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEpnTmtxMkhzbzNGOExh
            SjhEZk5KdEsrY0RnZDJwMkMxUTBIU3lweVZJCnQ3Ujd4ZnVpcW9TYjZiR2xoaG1n
            RXdiajB2MkordENkdlhhTlJER2dwcUkKLS0tIEQxUS9RYkVJWElwS2wvUFRPZ2FR
            WUlremcxK3R3dkkrUG5LVXYraXM3WFEKXe5SUotec2H3I3RvsNtnBt0zyVCdySMG
            L+z4YccTHAaV24HXbfZEWLVhMcGFxIYIsSHzY8MQfcoJKnJxDMYsUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13chrgdcw55zhzzmjtlu9jhmjn2lt55rrlkx0h7kpu2gnaaz6u52qwzd0qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXVsR0ZDSU9pVm0rMFBs
            TFFRbVJYRk1yZ0x5dndvUDRCNFA0WUJZZTI4CmhWZEV2ZXVWbjJ2aWZOZEhhR1pV
            aGxiSno4UkNwT05OeVdrVG9XTzY0QlEKLS0tIDdjZ3k2TE9LYlloa2krcXVZRHgx
            RmNQdHlYYWRoT0pxV2lSdzcwNnJaUmMKIOV8KBPITMjHef3Fk35TMizwJxUk0DS2
            a5/dkHbc2h17ZZdnf2ifRFGRHobOgFEdPaM17g9r4ei8d5PO764p6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T16:05:53Z"
    mac: ENC[AES256_GCM,data:u2JKoYd4QG9sBzngXImIaOWdSBbj52MDGbzHl31CCQEan7b/c0poREvSt3x1zIx5JVz11n69klhUL9SCm2Ct73V6zJeSmZHbQyrU50/LP+DZ0IJtskhDbjp52KOg86Gkh3HZFkPSIxOz1jqxdARWCO7c3E8OA1S+wOYTANFHc8U=,iv:x2budynezYXEwJcEWolxXEFwQ0JtIsQlkGmeG+d39Ek=,tag:Y1bUtIsJKjk4c9XvSWt+AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
